
import { CategoryData } from './types';

export const TOTALS = {
  threads: 1779,
  traffic: 9029,
  keywords: 39497,
};

export const CATEGORIES_DATA: CategoryData[] = [
  {
    name: 'Types of Ransomware',
    totalThreads: 54,
    sumOfTraffic: 6484,
    sumOfKeywords: 1492,
    avgKeywordPosition: 37.6,
    threadsInTop10: 6,
  },
  {
    name: 'Ransomware Protection and Prevention',
    totalThreads: 32,
    sumOfTraffic: 388,
    sumOfKeywords: 951,
    avgKeywordPosition: 7.1,
    threadsInTop10: 29,
  },
  {
    name: 'Ransomware Recovery and Removal',
    totalThreads: 43,
    sumOfTraffic: 290,
    sumOfKeywords: 677,
    avgKeywordPosition: 14.9,
    threadsInTop10: 27,
  },
  {
    name: 'Ransomware Impact on Businesses and Industries',
    totalThreads: 9,
    sumOfTraffic: 48,
    sumOfKeywords: 80,
    avgKeywordPosition: 12.2,
    threadsInTop10: 5,
  },
  {
    name: 'Ransomware Detection and Detection Tools',
    totalThreads: 11,
    sumOfTraffic: 31,
    sumOfKeywords: 291,
    avgKeywordPosition: 11.8,
    threadsInTop10: 6,
  },
  {
    name: 'Ransomware in Cloud and Backup Environments',
    totalThreads: 6,
    sumOfTraffic: 27,
    sumOfKeywords: 35,
    avgKeywordPosition: 12.5,
    threadsInTop10: 5,
  },
  {
    name: 'Ransomware Attacks and Case Studies',
    totalThreads: 10,
    sumOfTraffic: 5,
    sumOfKeywords: 78,
    avgKeywordPosition: 17.6,
    threadsInTop10: 1,
  },
  {
    name: 'Ransomware and Cybersecurity Strategies',
    totalThreads: 12,
    sumOfTraffic: 5,
    sumOfKeywords: 297,
    avgKeywordPosition: 26.4,
    threadsInTop10: 1,
  },
  {
    name: 'Ransomware Attack Vectors and Methods',
    totalThreads: 6,
    sumOfTraffic: 31,
    sumOfKeywords: 179,
    avgKeywordPosition: 8.7,
    threadsInTop10: 4,
  },
  {
    name: 'Ransomware in Specific Platforms and Devices',
    totalThreads: 5,
    sumOfTraffic: 27,
    sumOfKeywords: 69,
    avgKeywordPosition: 6.8,
    threadsInTop10: 4,
  },
  {
    name: 'Ransomware as a Service and Cybercrime Ecosystem',
    totalThreads: 9,
    sumOfTraffic: 0,
    sumOfKeywords: 208,
    avgKeywordPosition: 42.9,
    threadsInTop10: 0,
  },
  {
    name: 'Ransomware Education and Training',
    totalThreads: 8,
    sumOfTraffic: 16,
    sumOfKeywords: 0,
    avgKeywordPosition: 13.9,
    threadsInTop10: 6,
  },
  {
    name: 'Ransomware Legal and Regulatory Aspects',
    totalThreads: 2,
    sumOfTraffic: 1,
    sumOfKeywords: 8,
    avgKeywordPosition: 16.0,
    threadsInTop10: 1,
  },
  {
    name: 'Ransomware Protection Tools and Software',
    totalThreads: 4,
    sumOfTraffic: 34,
    sumOfKeywords: 184,
    avgKeywordPosition: 12.2,
    threadsInTop10: 3,
  },
  {
    name: 'Ransomware Impact on Backups',
    totalThreads: 2,
    sumOfTraffic: 19,
    sumOfKeywords: 19,
    avgKeywordPosition: 4.0,
    threadsInTop10: 2,
  },
  {
    name: 'Ransomware Trends and Statistics',
    totalThreads: 4,
    sumOfTraffic: 0,
    sumOfKeywords: 207,
    avgKeywordPosition: 43.2,
    threadsInTop10: 0,
  },
  {
    name: 'Ransomware Detection & Recovery for Enterprises',
    totalThreads: 2,
    sumOfTraffic: 7,
    sumOfKeywords: 19,
    avgKeywordPosition: 26.5,
    threadsInTop10: 1,
  },
  {
    name: 'Brand Competitors',
    totalThreads: 4,
    sumOfTraffic: 0,
    sumOfKeywords: 45,
    avgKeywordPosition: 53.0,
    threadsInTop10: 0,
  },
  {
    name: 'Other',
    totalThreads: 1556,
    sumOfTraffic: 1616,
    sumOfKeywords: 34658,
    avgKeywordPosition: 25.7,
    threadsInTop10: 432,
  },
];
